fixup: include workarounds from mongosh repo

diff --git a/.evergreen.yml b/.evergreen.yml
--- a/.evergreen.yml
+++ b/.evergreen.yml
@@ -55,6 +55,20 @@ functions:
           set -e
           set -x
 
+          rm -rf /tmp/m && mkdir -pv /tmp/m # Node.js compilation can fail on long path prefixes
+          trap "rm -rf /tmp/m" EXIT
+          export TMP=/tmp/m
+          export TMPDIR=/tmp/m
+
+          # The CI machines we have for Windows and x64 macOS are not
+          # able to compile OpenSSL with assembly support,
+          # so we revert back to the slower version.
+          if [ "$OS" == "Windows_NT" ]; then
+            export BOXEDNODE_CONFIGURE_ARGS='openssl-no-asm'
+          elif uname -a | grep -q 'Darwin.*x86_64'; then
+            export BOXEDNODE_CONFIGURE_ARGS='--openssl-no-asm'
+          fi
+
           . .evergreen/use-node.sh
           npm run build
           TEST_NODE_VERSION="$TEST_NODE_VERSION" npm run test-ci
